#!/bin/sh

# Parse colors from "~/.Xresources"
xrdb -override "${HOME}/.Xresources"

xrdb_query()
{
    [ -n "$XRDB_QUERY" ] || XRDB_QUERY="$(xrdb -query)"

    echo "$XRDB_QUERY" | while IFS=';' read -r STRING; do
        [ "${1}" = "${STRING%%\	*}" ] || continue
        echo "${STRING##*\	}"
        break
    done
}

getcolors()
{
    BACKGROUND="$(xrdb_query '*.background:')"
    UNFOCUS="$(xrdb_query '*.unfocus:')"
    FOCUS="$(xrdb_query '*.focus:')"
}

getcolors

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }

# ---Start some programs---

# Run keybindings daemon.
pgrep -x sxhkd > /dev/null || sxhkd &

# Run notification daemon.
dunst --config $HOME/.config/dunst/dunstrc &
#$HOME/.config/dunst/scripts/dunst_logger.sh &

# Run Picom.
picom --config $HOME/.config/picom/picom.conf &

# Execute bspwm-specific scripts.
bspfloat &

# Start X wallpaper.
feh --no-fehbg --bg-scale $HOME/.wallpapers/24.jpg

# Fix cursor.
xsetroot -cursor_name left_ptr 

# --- Window Rules ---
bspc monitor LVDS-1 -d 1 2 3 4 5 6

bspc wm -O LVDS-1 HDMI-1

rule -a kitty follow=on focus=on
rule -a firefox follow=on focus=on
rule feh state=floating

# --- General ---
config top_padding 33
config border_width 4
config window_gap 10
config split_ratio 0.50

config borderless_monocle true
config gapless_monocle true
config focus_follows_pointer false

bspc config normal_border_color "$UNFOCUS"
bspc config focused_border_color "$FOCUS"
config presel_feedback_color "$BACKGROUND"
